included:
  - vivobody
  - vivobodyTests
  - vivobodyUITests

excluded:
  - vivobody.xcodeproj

allow_zero_lintable_files: false
reporter: "xcode"
strict: true

disabled_rules:
  - static_over_final_class

opt_in_rules:
  - array_init
  - closure_spacing
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_try
  - force_unwrapping
  - modifier_order
  - sorted_imports
  - todo
  - vertical_whitespace_closing_braces

line_length:
  warning: 120
  error: 160
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

file_length:
  warning: 400
  error: 800

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 250
  error: 400

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - id
    - i
    - x
    - y
    - z
    - db
    - URL
  validates_start_with_lowercase: true

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

nesting:
  type_level:
    warning: 2

vertical_whitespace:
  max_empty_lines: 1
