#!/usr/bin/env python3
#
#  documentation_inventory.py
#  vivobody
#
#  Generates catalog counts and the complete scenario directory from authored
#  JSON. Documentation checks detect drift without building or launching the app.
#

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def cell(value: object) -> str:
    return str(value).replace("|", "&#124;").replace("\n", " ").replace("`", "&#96;")


def catalog_inventory(root: Path) -> str:
    catalog = root / "specs/catalog"
    muscles = read_json(catalog / "taxonomy.json")["muscles"]
    actions = read_json(catalog / "joint-actions.json")["actions"]
    sources = read_json(catalog / "evidence.json")["sources"]
    families = [(path, read_json(path)) for path in sorted((catalog / "families").glob("*.json"))]
    mesh_bases = {base for muscle in muscles for base in muscle.get("meshBaseNames", [])}
    lines = [
        "# Current catalog inventory", "",
        "- Status: Generated inventory", "",
        "Generated from the authored JSON by `Scripts/documentation_inventory.py`.",
        "Run `/usr/bin/python3 Scripts/documentation_inventory.py --write` from the",
        "repository root after catalog changes. Do not edit this file by hand.", "",
        "These are source counts, not biomechanical validation results. Use",
        "`/usr/bin/python3 Scripts/catalog.py --check` to validate the contracts and",
        "runtime parity. The synthetic validator fixture is excluded from this inventory.", "",
        "| Measure | Count |", "|---|---:|",
        f"| Reviewed families | {len(families)} |",
        f"| Exercises | {sum(len(family['exercises']) for _, family in families)} |",
        f"| Muscle regions | {len(muscles)} |",
        f"| Unique trainable mesh bases | {len(mesh_bases)} |",
        f"| Joint actions | {len(actions)} |",
        f"| Evidence sources | {len(sources)} |", "",
        "## Family roster", "",
        "| Family source | Exercises |", "|---|---:|",
    ]
    for path, family in families:
        lines.append(f"| [{cell(family['id'])}](families/{path.name}) | {len(family['exercises'])} |")
    lines.extend(["", "See [catalog foundations](README.md) for the contract and",
                  "[family history](family-roadmap.md) for past decisions.", ""])
    return "\n".join(lines)


def scenario_inventory(root: Path) -> str:
    scenarios = sorted((root / "Scripts/verify_scenarios").glob("*.json"))
    lines = [
        "# Scenario directory", "",
        "- Status: Generated inventory", "",
        "Generated by `Scripts/documentation_inventory.py`. Regenerate from the root",
        "with `/usr/bin/python3 Scripts/documentation_inventory.py --write`.", "",
        "Use the [feature map](README.md#choose-evidence-for-the-change) to choose a",
        "flow, then inspect its JSON for assertions and steps. This table records the",
        "initial launch only; later steps may navigate or relaunch with other settings.",
        "An omitted appearance or accessibility option is not evidence of coverage.",
        "Listing a scenario does not mean it has been run or its screenshots reviewed.", "",
        f"Scenario files: {len(scenarios)}.", "",
        "| Scenario | Initial tab | Initial launch arguments |", "|---|---|---|",
    ]
    for path in scenarios:
        scenario = read_json(path)
        launch = scenario["launch"]
        arguments = " ".join(launch.get("arguments", []))
        lines.append(
            f"| [{cell(path.stem)}]({path.name}) | {cell(launch.get('tab', 'unspecified'))} "
            f"| {('`' + cell(arguments) + '`') if arguments else 'None declared'} |"
        )
    return "\n".join(lines) + "\n"


def generated_documents(root: Path) -> dict[str, str]:
    return {
        "specs/catalog/inventory.md": catalog_inventory(root),
        "Scripts/verify_scenarios/index.md": scenario_inventory(root),
    }


def stale_documents(root: Path) -> list[str]:
    return [
        relative for relative, expected in generated_documents(root).items()
        if not (root / relative).is_file()
        or (root / relative).read_text(encoding="utf-8") != expected
    ]


def main(argv: list[str] | None = None, root: Path = ROOT) -> int:
    parser = argparse.ArgumentParser(description="Generate or check documentation inventories.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="Refresh the two generated Markdown inventories.")
    mode.add_argument("--check", action="store_true", help="Fail on stale inventory; default, read-only.")
    args = parser.parse_args(argv)
    try:
        if args.write:
            for relative, content in generated_documents(root).items():
                path = root / relative
                path.parent.mkdir(parents=True, exist_ok=True)
                if not path.is_file() or path.read_text(encoding="utf-8") != content:
                    path.write_text(content, encoding="utf-8")
                    print(f"Updated {relative}")
            return 0
        stale = stale_documents(root)
        for relative in stale:
            print(f"{relative}: stale; run /usr/bin/python3 Scripts/documentation_inventory.py --write", file=sys.stderr)
        if stale:
            return 1
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"Documentation inventory failed: {error}", file=sys.stderr)
        return 1
    print("Documentation inventories passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
